#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

[ "$TRAVIS" = true ] || cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew update

  brew bundle check 2>&1 >/dev/null || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [ "$TRAVIS" = true ]; then
  echo "==> THIS IS TRAVIS"
  echo "=>> Seeing up deps…"
  cp test/.envtravis .env
  export $(cat < .env)
elif  [ -f ".node-version" ] && [ -z "$(nodenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Node.js…"
  nodenv install --skip-existing
fi

if [ -f "package.json" ]; then
  echo "==> Installing module dependencies…"
  npm install
fi

