#!/bin/sh

# script/migration: Execute the migration script to update or downgrade database. 

set -e

cd "$(dirname "$0")/.."

echo "===> Migrating "$1" DB..."
node src/core/migration.js $1

echo "==> App is now ready to go!"


