#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

scripts/bootstrap

echo "===> Setting up DB..."
# reset database to a fresh state.
scripts/migration down
scripts/migration

if [ ! "$TRAVIS" = true ]; then
  # on travis we cannot init the submodule
  echo "===> Setting up Frontend..."
  git submodule update --init --recursive
  client/scripts/bootstrap
fi

echo "==> App is now ready to go!"

