#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

scripts/bootstrap

echo "==> Updating db..."
# run all database migrations to ensure everything is up to date.
scripts/migration
